[package]
name = "termsheets"
version = "0.1.0"
authors = ["Byron Wasti <byron.wasti@gmail.com>"]
edition = "2018"

[dependencies]
tui = "0.6.2"
termion = "1.5.3"
pest = "2.1.1"
pest_derive = "2.1.0"
chrono = "0.4.7"
fern = "0.5.8"
log = "0.4.8"
